name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

      
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: preZero Static Analysis
      run: |
        ${GITHUB_WORKSPACE}/sl --version
        ${GITHUB_WORKSPACE}/sl analyze --strict --verbose --wait \
          --app test-checkanalysis \
          --tag branch=${BRANCH_NAME} \
          --oss-project-dir . \
          .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
